services:
  - type: web
    name: swms
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_TOKEN_FOLDER
        value: /tmp/google_tokens
